CREATE TABLE users (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username                 VARCHAR(30)  NOT NULL,
    email                    VARCHAR(255) NOT NULL,
    password_hash            VARCHAR(72)  NOT NULL,
    accepted_privacy_version VARCHAR(20)  NOT NULL,
    accepted_privacy_at      TIMESTAMPTZ  NOT NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS 'Account holders. Personal data is limited to username and email.';
COMMENT ON COLUMN users.accepted_privacy_version IS 'Privacy policy version accepted at registration (LGPD consent record).';
COMMENT ON COLUMN users.accepted_privacy_at IS 'Moment the privacy policy was accepted.';
